### ISSUE TITLE
Add back commit history

### ISSUE THREAD

**Issue by drtshock** [Atilt/titaniumfactions#1]
You seem to be removing credit for code you're pushing. Please make sure that you restore commit history from before you forked, and rather than copy pasting code, merge commits from other forks so everyone gets the right credit <3

Love to see another fork going well!

**Comment by Driftay** [comment]
Agreed!

**Comment by ngel8844** [comment]
If it's an issue in copying small 1-2 line fix/implementations from the FUUID, I can start crediting such things in the code itself. As for previous commit history, the repo was cloned and forked, not a direct fork. 

Apologies for any confusion on what this may have come across as. I've attempted to make it transparent, if it isn't already obvious that this is a fork, will full origin credit to FUUID

**Comment by drtshock** [comment]
If it was a clone and fork, then we'd have commit history. The only way commit history would be removed is if you proactively deleted the .git folder before pushing to your own repo.
